# Generated by Django 2.2.4 on 2019-08-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tube_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='thumbs_down',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='thumbs_up',
        ),
        migrations.AddField(
            model_name='theme',
            name='media_thumbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tube',
            name='thumbs_down',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tube',
            name='thumbs_up',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tube',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
